from aiogram.fsm.state import State, StatesGroup

class RegistrationStates(StatesGroup):
    PHONE = State()
    FIRST_NAME = State()
    LAST_NAME = State()
    BIRTH_DATE = State()
    COUNTRY = State()
    CITY = State()
    ROLE = State()
    TRAINER_PRICE = State()
    SPORT = State()
    GENDER = State()
    PLAYER_LEVEL = State()
    PHOTO = State()
    SHOW_IN_SEARCH = State()
    VACATION_TENNIS = State()
    VACATION_START = State()
    VACATION_END = State()
    VACATION_COMMENT = State()
    COUNTRY_INPUT = State()
    CITY_INPUT = State()
    PROFILE_COMMENT = State()
    DEFAULT_PAYMENT = State()
    VACATION_COUNTRY = State()
    VACATION_COUNTRY_INPUT = State()
    VACATION_CITY = State()
    VACATION_CITY_INPUT = State()
    
    # Новые поля для знакомств
    DATING_GOAL = State()
    DATING_INTERESTS = State()
    DATING_ADDITIONAL = State()
    
    # Поля для встреч
    MEETING_TIME = State()
    
    # Поля для настольного тенниса (рейтинг)
    TABLE_TENNIS_RATING = State()

class GameOfferStates(StatesGroup):
    GAME_SPORT = State()
    GAME_COUNTRY = State()
    GAME_COUNTRY_INPUT = State()
    GAME_CITY = State()
    GAME_CITY_INPUT = State()
    GAME_DISTRICT = State()
    GAME_DATE = State()
    GAME_DATE_MANUAL = State()
    GAME_TIME = State()
    GAME_TYPE = State()
    PAYMENT_TYPE = State()
    GAME_COMPETITIVE = State()
    GAME_REPEAT = State()
    GAME_COMMENT = State()
    DATING_GOAL = State()
    DATING_INTERESTS = State()
    DATING_ADDITIONAL = State()

class SearchStates(StatesGroup):
    SEARCH_TYPE = State()
    SEARCH_COUNTRY = State()
    SEARCH_CITY = State()
    SEARCH_RESULTS = State()
    SEARCH_PROFILE = State()
    SEARCH_COUNTRY_INPUT = State()
    SEARCH_CITY_INPUT = State()
    SEARCH_NO_RESULTS = State()
    SEARCH_PRICE_RANGE = State()
    SEARCH_SPORT = State()

class EditProfileStates(StatesGroup):
    COMMENT = State()
    PAYMENT = State()
    PHOTO_UPLOAD = State()
    CITY = State()
    CITY_INPUT = State()
    COUNTRY = State()
    COUNTRY_INPUT = State()
    SPORT = State()
    ROLE = State()
    PRICE = State()
    LEVEL = State()
    DATING_GOAL = State()
    DATING_INTERESTS = State()
    DATING_ADDITIONAL = State()
    MEETING_TIME = State()

class PaymentStates(StatesGroup):
    WAITING_EMAIL = State()
    CONFIRM_PAYMENT = State()

class TournamentPaymentStates(StatesGroup):
    WAITING_EMAIL = State()
    CONFIRM_PAYMENT = State()

class AddScoreState(StatesGroup):
    selecting_game_type = State()
    selecting_partner = State()
    searching_partner = State()
    selecting_opponent = State()
    searching_opponent = State()
    selecting_set_score = State()
    adding_another_set = State()
    adding_media = State()
    confirming_score = State()
    searching_opponent1 = State()
    searching_opponent2 = State()
    selecting_opponent1 = State()
    selecting_opponent2 = State()
    # Состояния для турнирной игры
    selecting_tournament = State()
    selecting_tournament_opponent = State()
    
class SearchPartnerStates(StatesGroup):
    SEARCH_TYPE = State()
    SEARCH_COUNTRY = State()
    SEARCH_COUNTRY_INPUT = State()
    SEARCH_CITY = State()
    SEARCH_CITY_INPUT = State()
    SEARCH_SPORT = State()
    SEARCH_GENDER = State()
    SEARCH_LEVEL = State()
    SEARCH_PRICE_RANGE = State()
    SEARCH_RESULTS = State()
    SEARCH_NO_RESULTS = State()
    SEARCH_ERROR = State()
    SEARCH_OTHER_COUNTRIES = State()
    SEARCH_OTHER_CITIES = State()
    SEARCH_DISTRICT = State()
    # Специальные фильтры для знакомств
    SEARCH_AGE_RANGE = State()
    SEARCH_DATING_GOAL = State()
    SEARCH_DISTANCE = State()

class BrowseOffersStates(StatesGroup):
    SELECT_COUNTRY = State()
    ENTER_COUNTRY = State()
    SELECT_CITY = State()
    ENTER_CITY = State()
    SELECT_SPORT = State()

class RespondToOfferStates(StatesGroup):
    ENTER_COMMENT = State()

class BrowseToursStates(StatesGroup):
    SELECT_COUNTRY = State()
    ENTER_COUNTRY = State()
    SELECT_CITY = State()
    ENTER_CITY = State()
    SELECT_SPORT = State()

class CreateTourStates(StatesGroup):
    ENTER_START_DATE = State()
    ENTER_END_DATE = State()
    ENTER_COMMENT = State()
    SELECT_COUNTRY = State()
    ENTER_COUNTRY = State()
    SELECT_CITY = State()
    ENTER_CITY = State()

class AdminEditProfileStates(StatesGroup):
    SELECT_USER = State()
    COMMENT = State()
    PAYMENT = State()
    COUNTRY = State()
    COUNTRY_INPUT = State()
    CITY = State()
    CITY_INPUT = State()
    PHOTO_UPLOAD = State()
    SPORT = State()
    ROLE = State()
    TRAINER_PRICE = State()
    LEVEL = State()
    DATING_GOAL = State()
    DATING_INTERESTS = State()
    DATING_ADDITIONAL = State()
    MEETING_TIME = State()

class CreateTournamentStates(StatesGroup):
    SPORT = State()
    COUNTRY = State()
    COUNTRY_INPUT = State()
    CITY = State()
    CITY_INPUT = State()
    DISTRICT = State()
    TYPE = State()
    GENDER = State()
    CATEGORY = State()
    AGE_GROUP = State()
    DURATION = State()
    PARTICIPANTS_COUNT = State()
    SHOW_IN_LIST = State()
    HIDE_BRACKET = State()
    COMMENT = State()
    CONFIRM = State()

class EditTournamentStates(StatesGroup):
    SELECT_TOURNAMENT = State()
    EDIT_FIELD = State()
    EDIT_SPORT = State()
    EDIT_COUNTRY = State()
    EDIT_COUNTRY_INPUT = State()
    EDIT_CITY = State()
    EDIT_CITY_INPUT = State()
    EDIT_DISTRICT = State()
    EDIT_TYPE = State()
    EDIT_GENDER = State()
    EDIT_CATEGORY = State()
    EDIT_AGE_GROUP = State()
    EDIT_DURATION = State()
    EDIT_PARTICIPANTS_COUNT = State()
    EDIT_SHOW_IN_LIST = State()
    EDIT_HIDE_BRACKET = State()
    EDIT_COMMENT = State()
    MANAGE_PARTICIPANTS = State()
    ADD_PARTICIPANT = State()
    REMOVE_PARTICIPANT = State()

class ViewTournamentsStates(StatesGroup):
    SELECT_SPORT = State()
    SELECT_COUNTRY = State()
    COUNTRY_INPUT = State()
    SELECT_CITY = State()
    CITY_INPUT = State()
    SELECT_DISTRICT = State()
    SELECT_GENDER = State()
    SELECT_TYPE = State()
    VIEW_TOURNAMENT = State()

class AdminEditGameStates(StatesGroup):
    EDIT_SCORE = State()
    EDIT_MEDIA = State()
    EDIT_WINNER = State()
    